const products = [
    { id: 1, name: "Android Smartphone", price: 8999, img: "images/home-items/item-android-smartphone.jpg" },
    { id: 2, name: "Bluetooth Headset", price: 899, img: "images/home-items/item-bluetooth-headset.jpg" },
    { id: 3, name: "Capture Card", price: 2499, img: "images/home-items/item-capture-card.jpg" },
    { id: 4, name: "Car Phone Holder", price: 299, img: "images/home-items/item-car-phone-holder.jpg" },
    { id: 5, name: "Computer Case", price: 1899, img: "images/home-items/item-computer-case_.jpg" },
    { id: 6, name: "Cooling Fan", price: 799, img: "images/home-items/item-cooling-fan-cpu-cooler.jpg" },
    { id: 7, name: "CPU Processor", price: 5999, img: "images/home-items/item-cpu-processor.jpg" },
    { id: 8, name: "Gaming Chair", price: 4999, img: "images/home-items/item-gaming-chair.jpg" },
    { id: 9, name: "Gaming Headset", price: 1499, img: "images/home-items/item-gaming-headset.jpg" },
    { id: 10, name: "Gaming Keyboard", price: 1799, img: "images/home-items/item-gaming-keyboard_.jpg" },
    { id: 11, name: "Gaming Laptop", price: 42999, img: "images/home-items/item-gaming-laptop.jpg" },
    { id: 12, name: "Gaming Mouse", price: 899, img: "images/home-items/item-gaming-mouse.jpg" },
    { id: 13, name: "Gamepad Controller", price: 1199, img: "images/home-items/item-gamepad_.jpg" },
    { id: 14, name: "Graphics Card", price: 9999, img: "images/home-items/item-graphics-card.jpg" },
    { id: 15, name: "HDMI Cable", price: 249, img: "images/home-items/item-hdmi-cable_.jpg" },
    { id: 16, name: "Laptop Cooling Pad", price: 799, img: "images/home-items/item-laptop-cooling-pad.jpg" },
    { id: 17, name: "Microphone", price: 1399, img: "images/home-items/item-microphone_.jpg" },
    { id: 18, name: "Motherboard", price: 4999, img: "images/home-items/item-motherboard.jpg" },
    { id: 19, name: "Mouse Pad", price: 299, img: "images/home-items/item-mouse-pad_.jpg" },
    { id: 20, name: "Portable Monitor", price: 5999, img: "images/home-items/item-portable-monitor.jpg" },
    { id: 21, name: "Portable Projector", price: 5499, img: "images/home-items/item-portable-projector.jpg" },
    { id: 22, name: "Powerbank", price: 899, img: "images/home-items/item-powerbank.jpg" },
    { id: 23, name: "Power Supply", price: 2299, img: "images/home-items/item-power-supply_.jpg" },
    { id: 24, name: "RAM", price: 1599, img: "images/home-items/item-ram.jpg" },
    { id: 25, name: "RGB LED Strip", price: 499, img: "images/home-items/item-rgb-led-strip.jpg" },
    { id: 26, name: "Screen Protector", price: 199, img: "images/home-items/item-screen-protector_.jpg" },
    { id: 27, name: "Selfie Ring Light", price: 399, img: "images/home-items/item-selfie-ring-light.jpg" },
    { id: 28, name: "Smart TV Box", price: 1399, img: "images/home-items/item-smart-tv-box.jpg" },
    { id: 29, name: "Smartwatch", price: 1799, img: "images/home-items/item-smartwatch.jpg" },
    { id: 30, name: "SSD", price: 2399, img: "images/home-items/item-ssd.jpg" },
    { id: 31, name: "Streaming Camera", price: 2999, img: "images/home-items/item-streaming-camera.jpg" },
    { id: 32, name: "USB Flash Drive", price: 499, img: "images/home-items/item-usb-flash-drive_.jpg" },
    { id: 33, name: "VR Controller Set", price: 6999, img: "images/home-items/item-vr-controller-set.jpg" },
    { id: 34, name: "Webcam", price: 899, img: "images/home-items/item-webcam.jpg" },
    { id: 35, name: "Wireless Charger", price: 999, img: "images/home-items/item-wireless-charger.jpg" },
    { id: 36, name: "Wireless Earbuds", price: 1299, img: "images/home-items/item-wireless-earbuds.jpg" },
    { id: 37, name: "Wireless Mouse", price: 499, img: "images/home-items/item-wireless-mouse.jpg" },
    { id: 38, name: "External Hard Drive", price: 2999, img: "images/home-items/item-external-hard-drive_.jpg" },
    { id: 39, name: "Phone Case", price: 199, img: "images/home-items/item-phone-case_.jpg" },
    { id: 40, name: "Smart Light Box", price: 1599, img: "images/home-items/item-smart-tv-box.jpg" },
    { id: 41, name: "Arduino Uno", price: 399, img: "images/cart-images/item-arduino.png" },
    { id: 42, name: "Keyboard", price: 2199, img: "images/cart-images/item-keyboard.png" },
    { id: 43, name: "X-box Controller", price: 579, img: "images/cart-images/item-controller.png" },
    { id: 44, name: "24 inch Monitor", price: 4599, img: "images/cart-images/item-monitor.png" },
    { id: 45, name: "Instax", price: 2999, img: "images/cart-images/item-instax.png" },
    { id: 46, name: "JBL Speaker", price: 3499, img: "images/cart-images/item-jbl-speaker.png" },
    { id: 47, name: "iPhone 17 Pro Max", price: 115000, img: "images/cart-images/item-iphone.png" },
    { id: 48, name: "Type C Charger", price: 239, img: "images/cart-images/item-typec-charger.png" },
    { id: 49, name: "VR Headset", price: 5999, img: "images/cart-images/item-vr-headset.png" },
    { id: 50, name: "Desk Lamp", price: 379, img: "images/cart-images/item-desk-lamp.png" },
    { id: 51, name: "1TB HDD", price: 1399, img: "images/cart-images/item-HDD.png" },
    { id: 52, name: "USB Hub", price: 349, img: "images/cart-images/item-usb-hub.png" }
];